ccp_kernel_load: check for sudo and add help message for cmd line args

diff --git a/ccp_kernel_load b/ccp_kernel_load
--- a/ccp_kernel_load
+++ b/ccp_kernel_load
@@ -3,6 +3,22 @@ module="ccp"
 device="ccpkp"
 mode="664"
 
+usage() {
+    echo "usage: sudo ./ccp_kernel_load ipc=[0|1]"
+    echo "       netlink  : ipc=0"
+    echo "       char-dev : ipc=1"
+}
+
+if [ "$EUID" -ne 0 ]; then 
+    echo "error: must run as root"
+    usage
+    exit 1
+fi
+
+if [ "$#" -ne 1 ]; then
+    usage
+    exit 1
+fi
 
 # invoke insmod with all arguments we got
 # and use a pathname, as insmod doesn't look in . by default
diff --git a/ccp_kernel_unload b/ccp_kernel_unload
--- a/ccp_kernel_unload
+++ b/ccp_kernel_unload
@@ -2,6 +2,21 @@
 module="ccp"
 device="ccpkp"
 
+usage() {
+    echo "usage: sudo ./ccp_kernel_unload"
+}
+
+if [ "$EUID" -ne 0 ]; then 
+    echo "error: must run as root"
+    usage
+    exit 1
+fi
+
+if [ "$#" -ne 0 ]; then
+    usage
+    exit 1
+fi
+
 # invoke rmmod with all arguments we got
 /sbin/rmmod $module $* || exit 1
 
